### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by kush1434** [kush1434/kushs_2025#9]
- [ ] Find Car Listings API
- [ ] Filter Data so around 5 listings for hybrid, electric, and gas
- [ ] Choose whether pictures are wanted by discussing with the team, if so find the API with pictures
- [ ] Display data correctly on the webpage
- [ ] Style based on team pages format
